# Generated by Django 5.2.2 on 2026-02-05 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="clients.role",
            ),
        ),
    ]
