from rest_framework import serializers

from .models import Exercise, Workout, WorkoutLog


class WorkoutSerializer(serializers.ModelSerializer):
    class Meta:
        model = Workout
        fields = ["id", "title", "date"]


class ExerciseSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    name = serializers.CharField(max_length=100)
    exercise_type = serializers.ChoiceField(choices=Exercise.EXERCISE_TYPES)

    def validate_name(self, value):
        INVALID_EXERCISE_NAMES = ["sitting", "lying down"]
        if value in INVALID_EXERCISE_NAMES:
            raise serializers.ValidationError(
                "Exercise name cannot be 'sitting' or 'lying down'."
            )
        return value

    def create(self, validated_data):
        return Exercise.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.name = validated_data.get("name", instance.name)
        instance.exercise_type = validated_data.get(
            "exercise_type", instance.exercise_type
        )
        instance.save()
        return instance


# what we're going to do is serialize the data for workoutlog
class WorkoutLogReadOnlySerializer(serializers.ModelSerializer):
    # override the fields of workout and exercise using
    # the existing serializers.
    workout = WorkoutSerializer(read_only=True)
    exercise = ExerciseSerializer(read_only=True)
    # if you have many in the relationship
    # you need to add the many=True arguemnt to the serializer

    # write what you need for the serializer
    class Meta:
        model = WorkoutLog
        fields = [
            "id",  # auto generated by the model
            # these are the normal fields.
            "sets",
            "reps",
            "weight_kg",
            "time",
            # foreign key fields
            "workout",  # look above for the overide of the serialization
            "exercise",  # look above for the overide of the serialization
        ]


# create/update serializer (going to be used for
# post, patch, put deserialization.)
class WorkoutLogCreateUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = WorkoutLog
        fields = [
            "id",  # auto generated by the model
            # these are the normal fields.
            "sets",
            "reps",
            "weight_kg",
            "time",
            # foreign key fields
            "workout",
            "exercise",
            # these will only be the id.
        ]

    # note here inside of a model searilzer
    # the save/create/update methods are created
    # for you automatically.

    # validate that cardio workouts can't have weights
    # our specific platform
    # this is going to use multiple fields so we use the
    # validate method.
    def validate(self, data):
        exercise = data.get("exercise")  # none if not defined
        # check to see if this is a patch/put
        if self.instance and exercise is None:
            exercise = self.instance.exercise

        weight_kg = data.get("weight_kg")  # none if not defined

        # we're going to skip this if partial update
        # and those fields aren't defined.
        if exercise is None or weight_kg is None:
            # a successful result (return the data.)
            return data

        # right here we're going to permform the validation.
        if exercise.exercise_type == "cardio" and weight_kg is not None:
            # this is an error we need to raise it.
            raise serializers.ValidationError(
                "Cardio Exercises cannot have a weight",
            )

        # default of returning the data
        return data

    # let's validate that our system can't have more than 500 for weight
    # and can't be negative.
    def validate_weight_kg(self, value):
        # handle the negative case.
        if value is not None and value < 0:
            raise serializers.ValidationError("Weight can't be negative")
        # handle the case that it's can't be greater than 500
        elif value is not None and value > 500:
            raise serializers.ValidationError(
                "Come on. Weight can't be greater than 500",
            )
        # this is the positive.
        return value
