from rest_framework import serializers

from .models import Exercise, Workout, WorkoutLog


class WorkoutSerializer(serializers.ModelSerializer):
    class Meta:
        model = Workout
        fields = ["id", "title", "date"]


class ExerciseSerializer(serializers.Serializer):
    id = serializers.IntegerField(read_only=True)
    name = serializers.CharField(max_length=100)
    exercise_type = serializers.ChoiceField(choices=Exercise.EXERCISE_TYPES)

    def validate_name(self, value):
        INVALID_EXERCISE_NAMES = ["sitting", "lying down"]
        if value in INVALID_EXERCISE_NAMES:
            raise serializers.ValidationError(
                "Exercise name cannot be 'sitting' or 'lying down'."
            )
        return value

    def create(self, validated_data):
        return Exercise.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.name = validated_data.get("name", instance.name)
        instance.exercise_type = validated_data.get(
            "exercise_type", instance.exercise_type
        )
        instance.save()
        return instance


# what we're going to do is serialize the data for workoutlog
class WorkoutLogReadOnlySerializer(serializers.ModelSerializer):
    # override the fields of workout and exercise using
    # the existing serializers.
    workout = WorkoutSerializer(read_only=True)
    exercise = ExerciseSerializer(read_only=True)
    # if you have many in the relationship
    # you need to add the many=True arguemnt to the serializer

    # write what you need for the serializer
    class Meta:
        model = WorkoutLog
        fields = [
            "id",  # auto generated by the model
            # these are the normal fields.
            "sets",
            "reps",
            "weight_kg",
            "time",
            # foreign key fields
            "workout",  # look above for the overide of the serialization
            "exercise",  # look above for the overide of the serialization
        ]


# create/update serializer (going to be used for
# post, patch, put deserialization.)
class WorkoutLogCreateUpdateSerializer(serializers.ModelSerializer):
    class Meta:
        model = WorkoutLog
        fields = [
            "id",  # auto generated by the model
            # these are the normal fields.
            "sets",
            "reps",
            "weight_kg",
            "time",
            # foreign key fields
            "workout",
            "exercise",
            # these will only be the id.
        ]

    # note here inside of a model searilzer
    # the save/create/update methods are created
    # for you automatically.
